// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw835mP0OBrmeekFtlVWTrYunYM6Yn5P4',
    appId: '1:1041828195307:web:c776a59dd1ced49853c7ae',
    messagingSenderId: '1041828195307',
    projectId: 'onevision-82f24',
    authDomain: 'onevision-82f24.firebaseapp.com',
    storageBucket: 'onevision-82f24.appspot.com',
    measurementId: 'G-GX0BEKPGKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-t2dzU4tr1BB-Rfb6VBhy0W3zE_07PQ',
    appId: '1:1041828195307:android:8b776014eb6bdea553c7ae',
    messagingSenderId: '1041828195307',
    projectId: 'onevision-82f24',
    storageBucket: 'onevision-82f24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGWXn-gFHZKredJ2ISZrlC1Kzy46UPvo0',
    appId: '1:1041828195307:ios:cd7d4a36ab2bb45b53c7ae',
    messagingSenderId: '1041828195307',
    projectId: 'onevision-82f24',
    storageBucket: 'onevision-82f24.appspot.com',
    iosBundleId: 'com.example.oneVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGWXn-gFHZKredJ2ISZrlC1Kzy46UPvo0',
    appId: '1:1041828195307:ios:cd7d4a36ab2bb45b53c7ae',
    messagingSenderId: '1041828195307',
    projectId: 'onevision-82f24',
    storageBucket: 'onevision-82f24.appspot.com',
    iosBundleId: 'com.example.oneVision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw835mP0OBrmeekFtlVWTrYunYM6Yn5P4',
    appId: '1:1041828195307:web:7b0338bbb9b9aeb953c7ae',
    messagingSenderId: '1041828195307',
    projectId: 'onevision-82f24',
    authDomain: 'onevision-82f24.firebaseapp.com',
    storageBucket: 'onevision-82f24.appspot.com',
    measurementId: 'G-XY0ZQJNHBV',
  );
}
